### ISSUE TITLE
[SUGGESTION] Migrate zigpy-cc repository to upstream zigpy organization?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-cc#13]
@sanyatuning can I suggest that you please consider talking to @Adminiuga & @dmulcahey about the possibility of you joining the zigpy organization @ https://github.com/zigpy/ and maybe also having your zigpy-cc repository here on GitHub moved to the zigpy organization @ https://github.com/zigpy/ so that the mainstream copy of this repo will stay there as its upstream instead and owned by the upstream zigpy organization? 

That way all developers that are members in the zigpy organization can have write access to one or more projects that it own for collaboration as a community? Hope that you could all come to an agreement that will make everyone happy with continuing with working on the  zigpy-cc repository together without getting offended by any ownership conflicts.

PS: I also posted the same suggestion on zigpy repository by @zigpy org here https://github.com/zigpy/zigpy/issues/295

**Comment by sanyatuning** [comment]
Done!
