### ISSUE TITLE
HASS reverts to zigpy-cc 0.1.0 on reboot

### ISSUE THREAD

**Issue by danpowpow** [zigpy/zigpy-cc#29]
I follow the instructions to update zigpy-cc in my home assistant venv (hassbian):

Activate your python virtual env
Update package with pip
pip install zigpy-cc==x.x.x

but it doesn't remain after a reboot.
apols if this is a hass/venv issue rather than a zigpy-cc thing.

can anyone advise?

**Comment by sanyatuning** [comment]
Try start with: `hass --skip-pip`

**Comment by sanyatuning** [comment]
Or edit manifest.json in zha component.
