### ISSUE TITLE
Device support request: QBKG03LM + cc2530 only shows status, no control.

### ISSUE THREAD

**Issue by levran** [zigpy/zigpy-cc#38]
the switch QBKG03LM is successfully paired with cc2530 + cp2102, is shown in ZHA. When physically turning on / off, the status changes in the HA (0,108,2) interface. But changing the status from the HA interface does not lead to a physical switch. In addition, after a few seconds in the interface HA, the switch returns to its previous state.

https://user-images.githubusercontent.com/3389141/79025251-dc02d600-7b8d-11ea-9660-86faef44a830.png

**Comment by sanyatuning** [comment]
@levran did you test conbee with ZHA integration or with deconz?

**Comment by sanyatuning** [comment]
https://github.com/zigpy/zha-device-handlers/pull/349
